# Scalers

In [1]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(4.0)

x + y, x * y, x / y, x ** y

(tensor(7.), tensor(12.), tensor(0.7500), tensor(81.))

# Vector

In [2]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [4]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A.T

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

# Tensor

In [5]:
tensor = torch.arange(24).reshape(2, 3, 4)
tensor

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [8]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()

A, B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0., 1., 2.],
         [3., 4., 5.]]))

In [7]:
# Hadamard Product

A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [10]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(torch.Size([2, 3, 4]), torch.Size([2, 3, 4]))

# Reduction

In [13]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum(), x.mean()

(tensor([0., 1., 2.]), tensor(3.), tensor(1.))

# Dot Product

In [14]:
y = torch.ones(3, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))