# Deep Learning Building Blocks:

## Affine maps:
One of the core workhorse of deep learning is the affine maps, which is a function f(x) where,<br>
```f(x) = Ax + b```
Here, A is a matrix and vectors x and b. The parameter to be learned here A and b, b is referred to as the bias term.

https://docs.pytorch.org/tutorials/beginner/nlp/deep_learning_tutorial.html


In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [18]:
lin = nn.Linear(3, 1)
print("Deep learning layer: ", lin)
print(lin.weight)
print(lin.bias)

data = torch.randn(2, 3)
print("\n\nInput data:", data)
print(lin(data))

Deep learning layer:  Linear(in_features=3, out_features=1, bias=True)
Parameter containing:
tensor([[-0.4591,  0.5020, -0.3513]], requires_grad=True)
Parameter containing:
tensor([-0.2258], requires_grad=True)


Input data: tensor([[-0.4699, -1.6271, -0.1127],
        [ 1.5980, -0.8445, -1.0489]])
tensor([[-0.7872],
        [-1.0148]], grad_fn=<AddmmBackward0>)
