In [9]:
import torch
import torch.nn as nn

layer = nn.Linear(10, 5)
activation = nn.ReLU()

# create a random input tensor: batch_size=3, input_features=10
input_tensor = torch.randn(3, 10)

# forward pass
output = activation(layer(input_tensor))
print(output.shape)  # torch.Size([3, 5])


torch.Size([3, 5])


In [11]:
layer = nn.Linear(8, 2)
print(layer.weight)

Parameter containing:
tensor([[-0.1723,  0.2226,  0.2592,  0.1326,  0.1166, -0.3343,  0.3287,  0.2481],
        [ 0.0665, -0.1828, -0.2490, -0.2718, -0.2997,  0.1074, -0.0170, -0.2065]],
       requires_grad=True)


In [12]:
import torch.nn.init as init
init.kaiming_uniform_(layer.weight)
print(layer.weight)
layer = nn.Linear(8, 2)
print(layer.weight)

Parameter containing:
tensor([[ 0.7246,  0.6103, -0.6459, -0.6165, -0.2511,  0.2983,  0.5077,  0.5847],
        [ 0.3135,  0.0143, -0.6178,  0.3110,  0.5424, -0.2889,  0.0143, -0.5892]],
       requires_grad=True)
Parameter containing:
tensor([[-0.0247,  0.1733,  0.2932,  0.0539, -0.2341, -0.1810, -0.2796, -0.0529],
        [ 0.3090, -0.0114, -0.3101, -0.2495,  0.3203, -0.2836, -0.2720,  0.0988]],
       requires_grad=True)
